version: "3.9"

networks:
  development:
    driver: bridge

services:
  #############
  ## Backend ##
  #############

  sabi:
    build:
      context: .
      dockerfile: Containerfile
    image: sabi:1.0
    env_file:
      - .env
    expose:
      - 3030
    networks:
      - development
    depends_on:
      - redis
    container_name: sabi-server

  #################
  ## Persistence ##
  #################

  redis:
    image: redis:6-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    networks:
      - development
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 15
    container_name: sabi-redis
