
@baseUrl = http://localhost:3030

###

GET {{baseUrl}}/doesnotexist HTTP/1.1
Accept: application/json
Content-Type: application/json

###

GET {{baseUrl}}/hello HTTP/1.1
Accept: application/json
Content-Type: application/json

###

GET {{baseUrl}}/health HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "status": "OK"
}

###

POST {{baseUrl}}/hello HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "Dario"
}


###

POST {{baseUrl}}/goodbye HTTP/1.1
Accept: application/json
Content-Type: application/json

###

POST {{baseUrl}}/goodbye/reason HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "reason": "Bye bye"
}
